### ISSUE TITLE
how can update json files without generating again the images after upload image to pinata

### ISSUE THREAD

**Issue by icar112** [galperins4/NFT_Generator#6]
Hello sir, thank you for the beautiful script. It really helped me to complete the work. I only have a question, how can I update the metadata hash after uploading the images, because according to what I understood, after the task of creating the images is finished, I upload it to a pinata, and then I take the hash and put it in a file nft.py and restart the file again, but how can I update the jason files without reproducing the images again, because in this case I used 1500px X 1500px images, and it produced about 10,000 and took me about two days of work.. I mean, it needs the same period Just for the sake of updating the jason files, the question is how can I update the jason files without generating the images again. Thank you, sorry for the length.

**Comment by galperins4** [comment]
Could you potentially include more details or a screenshot of your issue? The script should automatically populate the hash info for metadata when it is uploading into piñata so you shouldn't have to do it manually in the nft.py file.

**Comment by icar112** [comment]
Thank you sir for the reply ♥ 
These screenshots are from inside a file: nft.py I just added code of PINATA_JWT  

after save change im go to run nft.py like that : 

![image](https://user-images.githubusercontent.com/81950734/149638339-a316218e-357a-4417-9c87-d5647e0ecb65.png)

after finish generate . this is result : 

cmd :
![image](https://user-images.githubusercontent.com/81950734/149638414-4197eabc-c08b-4320-8bfc-1e6fdc441956.png)

from image : 
![image](https://user-images.githubusercontent.com/81950734/149638429-94a011a9-6c8b-4dae-b196-a8a6305ef035.png)

from meta data : 

![image](https://user-images.githubusercontent.com/81950734/149638448-03613e11-20f7-4201-84e2-4c133085d48e.png)

inside file metadata : 

![image](https://user-images.githubusercontent.com/81950734/149638464-11d61932-5486-4739-abe9-e94d10eaf95a.png)

from pinata, panel empty : 

![image](https://user-images.githubusercontent.com/81950734/149638517-21a1a5bc-1505-4293-a9dd-648a3090cfbb.png)

but after see nothing in pinata look what i do , im go to upload first of all image folder like that : 

![image](https://user-images.githubusercontent.com/81950734/149638584-eb9292c2-f0ac-4e6f-8ff9-9794e5e285bf.png)
 
 his give me hash CID : QmV6As78CmZ3ctRAe7qbzeyDfigFpqGZsyZXnqwSMX9x3c 
and im go to copy patse in nft.py like that : 

after save file nft.py im go to run , but im not push "Y" im go to push "N" like what read in readfile.txt :

![image](https://user-images.githubusercontent.com/81950734/149638672-5e667c6b-c919-46a8-aabd-233e798c0da3.png)

after that im go to see what change .. but nothing all less like before , after that im go to run again file nft.py but this time im push "Y" to see what can change : 

after that what change ?  his start generating again second time image and success copy CID hash to metadata .. 

![image](https://user-images.githubusercontent.com/81950734/149638789-36d7bede-ec0f-408c-b472-d852affb8ad0.png)

my question is how can only add CID hash in metadata without start generating image again because his take long time to finish generating 10000 image .. because im upload image before in pinata i want only copy and paste CID hash ..

thank you sir ♥

**Comment by galperins4** [comment]
ok -  I think I know what you want to do. So the way the script works is Piñata lets you 'pin' a file that has already been uploaded to IPFS that it can find. 

The present functionality of the script assumes that for uploading to IPFS, NFT.Storage is being used. Once the files are created and uploaded it grabs the new hash. This hash is what is used by the Piñata upload to pin. So essentially if you are planning to use Piñata you also need to use NFT.Storage as the primary upload to IPFS with this script. Then it will automatically take care of the uploading for you. 

If you aren't using NFT.Storage for IPFS, then this script doesn't have the has to put in the metadata files and auto-upload to the Piñata service. Unfortunately that means you would have to run the script another time for the 10,000 NFT's, upload to NFT.Storage, and then pin to Piñata.

**Comment by icar112** [comment]
Thank you for the reply.. Frankly, I am a little confused as to how to start with the right steps.. I don't know where to start
First, I created a new account in nft.storage. I created a new API and moved it to the NFT.py file.. What do I do now?

im try to generate now nft image and upload image to nft.storage .. but not like pinata by folder .. only image one by one .. imagine i have 10000 image Oo . all of them uploaded one by one to nft.storage? 

please can u tell me step by step how start with right steps ? if you have any video for that show me  please ..
im sorry for this confused ..

thank you sir .. ♥

**Comment by galperins4** [comment]
HI! I'm not entirely sure why you would need to upload one by one. If possible - could you let me know if it's possible to chat on discord about this? If you let me know your name and the server you are on I can try to contact you and it would be easier to troubleshoot

**Comment by icar112** [comment]
Yes sir, with great pleasure and joy, my discord account: ICARCOIN
I appreciate your kindness and generosity ♥

**Comment by galperins4** [comment]
what discord server are you on?

**Comment by icar112** [comment]
ICARCOIN 
:)

**Comment by icar112** [comment]
![image](https://user-images.githubusercontent.com/81950734/149855226-453b7f9a-861d-44bd-96ef-79144849db48.png)

**Comment by icar112** [comment]
What do you think that we use Telegram? I think it's easier to share the screen..or to use teamviewer ?

**Comment by galperins4** [comment]
Discord works... can you send an invite link to the ICARCOIN community discord and then I'll join and message you there?
